services:
  - type: web
    name: fpl-leaderboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 180 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
